FROM node:8 AS front-builder
WORKDIR /opt/front
ADD ./package.json /opt/front
RUN npm install

ADD . /opt/front
RUN npm run build-staging

FROM nginx:1.13-alpine
RUN mkdir -p /var/www/frontend
ADD ./docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=front-builder /opt/front/dist /var/www/frontend
EXPOSE 80
