/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface LocationReq {
  children?: Array<LocationReq>;
  fias?: string;
  id?: number;
  level?: number;
  name?: string;
  okato?: string;
  oktmo?: string;
  parent?: LocationReq;
  population?: number;
  type?: string;
}
